#ifndef WIFI_FORM_H
#define WIFI_FORM_H

#include <Arduino.h>

// The HTML content for the Wifi form.
const String kWifiForm =
    "<!DOCTYPE html>\n"
    "<html>\n"
    "    <head>\n"
    "        <title>Accent Wifi Setup</title>\n"
    "        <style>\n"
    "            body {\n"
    "                background-color: white;\n"
    "                font-family: 'Roboto', sans-serif;\n"
    "                font-weight: 400;\n"
    "                font-size: 12pt;\n"
    "                padding: 12pt;\n"
    "            }\n"
    "\n"
    "            input {\n"
    "                font-family: 'Roboto', sans-serif;\n"
    "                font-size: 12pt;\n"
    "                padding: 4pt;\n"
    "                margin-bottom: 12pt;\n"
    "                background-color: white;\n"
    "            }\n"
    "\n"
    "            input[type=text], input[type=password] {\n"
    "                border: 1pt solid black;\n"
    "                font-weight: 400;\n"
    "            }\n"
    "\n"
    "            input[type=submit] {\n"
    "                border: 2pt solid black;\n"
    "                font-weight: 700;\n"
    "                width: 100pt;\n"
    "            }\n"
    "\n"
    "            label {\n"
    "                font-weight: 700;\n"
    "                margin: 4pt;\n"
    "            }\n"
    "        </style>\n"
    "    </head>\n"
    "    <body>\n"
    "        <form method=\"post\" action=\"/save\">"
    "            <label for=\"ssid\">SSID:</label>"
    "            <input type=\"text\" name=\"ssid\" size=\"20\""
    " placeholder=\"SSID\"><br />"
    "            <label for=\"password\">Password:</label>"
    "            <input type=\"password\" name=\"password\" size=\"20\""
    " placeholder=\"Password\"><br />"
    "            <input type=\"submit\" value=\"Save\" />"
    "        </form>"
    "    </body>\n"
    "</html>\n";

#endif  // WIFI_FORM_H
