runtime: python39

instance_class: F1

handlers:
- url: /favicon\.ico
  mime_type: image/x-icon
  static_files: favicon.ico
  upload: favicon\.ico
- url: /robots\.txt
  mime_type: text/plain
  static_files: robots.txt
  upload: robots\.txt
- url: /sitemap\.txt
  mime_type: text/plain
  static_files: sitemap.txt
  upload: sitemap\.txt
- url: /marker\.png
  mime_type: image/png
  static_files: assets/marker.png
  upload: assets/marker\.png
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
