[build-system]
requires = ['setuptools==68.2.2', 'wheel==0.41.3', 'numpy==1.26.1']
build-backend = 'setuptools.build_meta'

[project]
name = 'dithering'
version = '1.0.0'
description = 'Floyd-Steinberg dithering written in C'
dependencies = ['numpy==1.26.1']
