[build-system]
requires = ['setuptools', 'wheel', 'numpy']
build-backend = 'setuptools.build_meta'

[project]
name = 'dithering'
version = '1.0.0'
description = 'Floyd-Steinberg dithering written in C'
dependencies = ['numpy']
