name: Deploy Server to Google App Engine

on:
  push:
    branches:
      - master
    paths:
      - 'server/**'
      - '.github/workflows/deploy-server.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
        credentials_json: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}

    - name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@v2
      with:
        project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
        working_directory: ./server
